main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
load: startup
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
# cmd
  massivecore.basecommand: {description: use the MassiveCore base command, default: false}
  massivecore.test: {description: run developer test, default: false}
  massivecore.id: {description: see the server id, default: false}
  massivecore.hearsound: {description: hear a sound, default: false}
  massivecore.store: {description: use the mstore command, default: false}
  massivecore.store.stats: {description: show mstore statistics, default: false}
  massivecore.store.listcolls: {description: list collections in a database, default: false}
  massivecore.store.copydb: {description: copy database content, default: false}
  massivecore.store.clean: {description: clean database, default: false}
  massivecore.usys: {description: use the usys command, default: false}
  massivecore.usys.multiverse: {description: manage multiverses, default: false}
  massivecore.usys.multiverse.list: {description: list multiverses, default: false}
  massivecore.usys.multiverse.show: {description: show multiverse, default: false}
  massivecore.usys.multiverse.new: {description: create new multiverse, default: false}
  massivecore.usys.multiverse.del: {description: delete multiverse, default: false}
  massivecore.usys.universe: {description: manage universes, default: false}
  massivecore.usys.universe.new: {description: create new universe in multiverse, default: false}
  massivecore.usys.universe.del: {description: delete universe in multiverse, default: false}
  massivecore.usys.universe.clear: {description: clear universe in multiverse, default: false}
  massivecore.usys.world: {description: set a worlds universe in a multiverse, default: false}
  massivecore.usys.aspect: {description: manage aspects, default: false}
  massivecore.usys.aspect.list: {description: list aspects, default: false}
  massivecore.usys.aspect.show: {description: show aspect, default: false}
  massivecore.usys.aspect.use: {description: set multiverse for aspect, default: false}
  massivecore.buffer: {description: use the buffer command, default: false}
  massivecore.buffer.print: {description: print buffer, default: false}
  massivecore.buffer.clear: {description: clear buffer, default: false}
  massivecore.buffer.set: {description: set buffer, default: false}
  massivecore.buffer.add: {description: add to buffer, default: false}
  massivecore.buffer.whitespace: {description: add whitespace to buffer, default: false}
  massivecore.cmdurl: {description: run all lines of url content, default: false}
  massivecore.config: {description: edit config, default: false}
  massivecore.sponsor: {description: toggle sponsor message, default: false}
  massivecore.click: {description: click, default: false}
  massivecore.version: {description: diplay plugin version, default: false}
# misc
  massivecore.notpdelay: {description: teleport without delay, default: false}
  massivecore.variable.book: {description: replace ***book*** with content of book in your hand, default: false}
  massivecore.variable.buffer: {description: replace ***buffer*** with content of your buffer, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  massivecore.*:
    default: false
    children:
      massivecore.basecommand: true
      massivecore.test: true
      massivecore.id: true
      massivecore.hearsound: true
      massivecore.store: true
      massivecore.store.stats: true
      massivecore.store.listcolls: true
      massivecore.store.copydb: true
      massivecore.store.clean: true
      massivecore.usys: true
      massivecore.usys.multiverse: true
      massivecore.usys.multiverse.list: true
      massivecore.usys.multiverse.show: true
      massivecore.usys.multiverse.new: true
      massivecore.usys.multiverse.del: true
      massivecore.usys.universe: true
      massivecore.usys.universe.new: true
      massivecore.usys.universe.del: true
      massivecore.usys.universe.clear: true
      massivecore.usys.world: true
      massivecore.usys.aspect: true
      massivecore.usys.aspect.list: true
      massivecore.usys.aspect.show: true
      massivecore.usys.aspect.use: true
      massivecore.buffer: true
      massivecore.buffer.print: true
      massivecore.buffer.clear: true
      massivecore.buffer.set: true
      massivecore.buffer.add: true
      massivecore.buffer.whitespace: true
      massivecore.cmdurl: true
      massivecore.config: true
      massivecore.sponsor: true
      massivecore.click: true
      massivecore.version: true
      massivecore.notpdelay: true
      massivecore.variable.book: true
      massivecore.variable.buffer: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massivecore.kit.operator:
    default: op
    children:
      massivecore.*: true
  massivecore.kit.rank3:
    default: false
    children:
      massivecore.store.clean: true
      massivecore.kit.rank2: true
  massivecore.kit.rank2:
    default: false
    children:
      massivecore.kit.rank1: true
  massivecore.kit.rank1:
    default: false
    children:
      massivecore.kit.rank0: true
      massivecore.id: true
      massivecore.store: true
      massivecore.store.stats: true
      massivecore.store.listcolls: true
      massivecore.usys: true
      massivecore.usys.multiverse: true
      massivecore.usys.multiverse.list: true
      massivecore.usys.multiverse.show: true
      massivecore.usys.aspect: true
      massivecore.usys.aspect.list: true
      massivecore.usys.aspect.show: true
      massivecore.buffer: true
      massivecore.buffer.print: true
      massivecore.buffer.clear: true
      massivecore.buffer.set: true
      massivecore.buffer.add: true
      massivecore.buffer.whitespace: true
      massivecore.notpdelay: true
      massivecore.variable.book: true
      massivecore.variable.buffer: true
  massivecore.kit.rank0:
    default: false
    children:
      massivecore.basecommand: true
      massivecore.hearsound: true
      massivecore.click: true
      massivecore.version: true
  massivecore.kit.default:
    default: true
    children:
      massivecore.kit.rank0: true
